/**
 * Action Types Constants
 * https://redux.js.org/basics/actions
 */

const JukeboxConstants = {
  GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAILED: 'GET_CATEGORIES_FAILED',
  GET_CATEGORY_PLAYLIST_REQUEST: 'GET_CATEGORY_PLAYLIST_REQUEST',
  GET_CATEGORY_PLAYLIST_SUCCESS: 'GET_CATEGORY_PLAYLIST_SUCCESS',
  GET_CATEGORY_PLAYLIST_FAILED: 'GET_CATEGORY_PLAYLIST_FAILED',
}

export default JukeboxConstants;
